/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { BaseLeagueContract } from "./BaseLeague";
import { LeagueContract } from "./League";
import { LeagueFactoryContract } from "./LeagueFactory";
import { MigrationsContract } from "./Migrations";
import { SeasonLeagueContract } from "./SeasonLeague";
import { WeeklyLeagueContract } from "./WeeklyLeague";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "BaseLeague"): BaseLeagueContract;
      require(name: "League"): LeagueContract;
      require(name: "LeagueFactory"): LeagueFactoryContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "SeasonLeague"): SeasonLeagueContract;
      require(name: "WeeklyLeague"): WeeklyLeagueContract;
    }
  }
}

export { BaseLeagueContract, BaseLeagueInstance } from "./BaseLeague";
export { LeagueContract, LeagueInstance } from "./League";
export { LeagueFactoryContract, LeagueFactoryInstance } from "./LeagueFactory";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { SeasonLeagueContract, SeasonLeagueInstance } from "./SeasonLeague";
export { WeeklyLeagueContract, WeeklyLeagueInstance } from "./WeeklyLeague";
